name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Adjust version as needed


      - name: Build
        run: |
            cd AWSServerless3
            dotnet restore
            dotnet build 

      - name: Publish
        run: |
            cd AWSServerless3
            dotnet publish
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAXB6PPKA5TC5QBS2T
          aws-secret-access-key: 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
          aws-region: ap-southeast-1 
      - run: cd AWSServerless3 && dotnet restore
      - run: zip -r publish.zip ./AWSServerless3/*
      - run: aws lambda update-function-code --function-name=HelloWorld-HelloWorldFunction-QZppcAMFCtKI  --zip-file=fileb://publish.zip 
