name: .NET

on:
  push:
    branches: [ main ]
defaults:
  run:
    working-directory: ./AWSServerless3

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./AWSServerless3
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore Services.sln
    - name: Build
      run: dotnet build --no-restore Services.sln
    - name: Deploy to Lambda
      working-directory: ./Services/ApiServices
      run: dotnet lambda deploy-serverless
