name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Adjust version as needed
      - name: Build
        run: |
            cd AWSServerless3
            dotnet restore
            dotnet build 

      - name: Publish
        run: |
            cd AWSServerless3
            dotnet publish
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
      - run: cd AWSServerless3 && dotnet restore
      - run: zip -r publish.zip ./AWSServerless3/*
      - run: aws lambda update-function-code --function-name=sam-app-AspNetCoreFunction-WCwiwnDGkUhJ  --zip-file=fileb://publish.zip 
